import os

BOT_ID = os.environ.get("COZE_BOT_ID", "7644058406282149938")
ACCESS_TOKEN = os.environ.get("COZE_ACCESS_TOKEN", "pat_9kMAfQiouvS95WP5GIik52Lgno5F78IZ0BRTw5Bbtc8dtfkNrBoQYl1Vp8nCl2li")

WS_URL = f"wss://ws.coze.cn/v1/chat?bot_id={BOT_ID}"

INPUT_AUDIO_FORMAT = "pcm"
INPUT_AUDIO_CODEC = "pcm"
INPUT_SAMPLE_RATE = 24000
INPUT_CHANNELS = 1
INPUT_BIT_DEPTH = 16
INPUT_CHUNK_SIZE = 4800

OUTPUT_AUDIO_CODEC = "pcm"
OUTPUT_SAMPLE_RATE = 24000
OUTPUT_CHANNELS = 1
OUTPUT_BIT_DEPTH = 16

VAD_SILENCE_DURATION_MS = 500
VAD_PREFIX_PADDING_MS = 600

PCM_BYTES_PER_SAMPLE = INPUT_BIT_DEPTH // 8
CHUNK_DURATION_MS = int(INPUT_CHUNK_SIZE / (INPUT_SAMPLE_RATE * INPUT_CHANNELS * PCM_BYTES_PER_SAMPLE) * 1000)

FRAMES_PER_BUFFER = INPUT_CHUNK_SIZE // (INPUT_CHANNELS * PCM_BYTES_PER_SAMPLE)